### ISSUE TITLE
1.9.0 causes crashes on blackberry priv

### ISSUE THREAD

**Issue by dipaw** [googlevr/cardboard#310]
### SMARTPHONE (please complete the following information):
- Device:  Blackberry Priv
- OS Android
- OS version 6

### STEPS TO REPRODUCE THE ISSUE
update any project to 1.9.0

### VERSIONS USED
**What version of Google Cardboard are you using?**
1.9.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2021.1.24f

- Select in which graphics API you can reproduce the bug.
   OpenGL ES3

### ADDITIONAL CONTEXT
After updating the cardboard package from 1.4.0 to 1.9.0, application began to crash. 

logcat 
11.08 20:48:36.455 18940 18955 Info Unity [XR] [CardboardXrInputProvider]: Lifecycle started
11.08 20:48:36.459 18940 18955 Debug Unity Choreographer available: Enabling VSYNC timing
11.08 20:48:36.473 18940 19000 Info CardboardSDK Android gyro bias is: -0.003196, -0.007457, 0.002131
11.08 20:48:36.497 18940 18990 Info Unity [XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
11.08 20:48:36.498 18940 18990 Debug CardboardParamsUtils Reading device parameters from external storage.
11.08 20:48:36.502 18940 18990 Debug CardboardParamsUtils Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params: open failed: EACCES (Permission denied)
11.08 20:48:36.539 18940 18990 Fatal art art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/com.laputais.deadlysins-2/base.apk)
11.08 20:48:36.539 18940 18990 Fatal art art/runtime/java_vm_ext.cc:410]   at void com.google.cardboard.proto.CardboardDevice$DeviceParams.<clinit>() (CardboardDevice.java:2243)
11.08 20:48:36.539 18940 18990 Fatal art art/runtime/java_vm_ext.cc:410]   at com.google.cardboard.proto.CardboardDevice$DeviceParams com.google.cardboard.sdk.deviceparams.DeviceParamsUtils.parseCardboardDeviceParams(byte[]) (DeviceParamsUtils.java:42)

**Comment by jballoffet** [comment]
Thanks @dipaw for reaching out. It seems that the issue was caused due to bump in the Protobuf version performed in 1.5.0 (https://github.com/googlevr/cardboard/releases/tag/v1.5.0). Could you please try the versions between 1.4.0 and 1.9.0 so as to find the culprit one? Does this issue take place when using the HelloCardboard sample scene?

Moreover, you could try the fix suggested [here](https://github.com/googlevr/cardboard/issues/258#issuecomment-881028098) to fix issues on Android 6, which consists basically in bumping the Protobuf dependency version to 3.10.0.

**Comment by dipaw** [comment]
> Moreover, you could try the fix suggested [here](https://github.com/googlevr/cardboard/issues/258#issuecomment-881028098) to fix issues on Android 6, which consists basically in bumping the Protobuf dependency version to 3.10.0.

Yes, it really worked! Thanks!
